# Generated by Django 4.2.7 on 2023-11-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("t9ser_api", "0002_match_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermatch",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
